version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

hooks:
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu

  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: ./codedeploy/restartTomcat.sh
      timeout: 180
      runas: ubuntu

  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu

  ValidateService:
    - location: ./codedeploy/validateService.sh
      timeout: 180
      runas: ubuntu
